### ISSUE TITLE
Unable to write multiline text

### ISSUE THREAD

**Issue by Elinchi** [Snoozeds/UnrealLocresEditor#1]
When I try to write multiline text, pressing Enter or Shift+Enter moves me to the next cell instead of starting a new line within the same cell. This prevents me from adding line breaks in the text.

**Comment by Snoozeds** [comment]
Fixed with commit [d02228a](https://github.com/Snoozeds/UnrealLocresEditor/commit/d02228ac69c1e724fdd2df2485686dfd916eae83), will release a new version soon. Thanks
